# Generated by Django 4.2.5 on 2023-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_video_transcode_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="transcode_pipeline",
            field=models.CharField(
                blank=True,
                choices=[("AWS", "AWS"), ("Peertube", "Peertube")],
                help_text="Transcode pipeline for this video",
                max_length=255,
                null=True,
                verbose_name="transcode pipeline",
            ),
        ),
    ]
